osx_image: xcode10.1
language: swift
xcode_scheme: 'CleanSwiftExample'
xcode_project: 'CleanSwiftExample.xcodeproj'
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
enableCodeCoverage: YES
before_install: 
  - rvm use $RVM_RUBY_VERSION
install: 
 - gem install slather 
 - bundle install --without=documentation --path ../travis_bundle_dir
after_success: 
 - slather coverage -s
 - bash <(curl -s https://codecov.io/bash) -f path/to/xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
 